export const GAME_STATE = "GAME_STATE";
export const PLAYER_ONE_STATE = "PLAYER_ONE_STATE";
export const PLAYER_TWO_STATE = "PLAYER_TWO_STATE";
export const PLAYER_ONE_ACTION = "PLAYER_ONE_ACTION";
export const PLAYER_TWO_ACTION = "PLAYER_TWO_ACTION";
export const PLAYER_ONE_INDEX = "PLAYER_ONE_INDEX";
export const PLAYER_TWO_INDEX = "PLAYER_TWO_INDEX";
